model:
  type: VISION_CLS
  name: resnet20_cifar10_new
  params:
    pretrained: True
    num_classes: 10

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.001
  precision: 16
  max_epochs: 700
  val_every_n_epochs: 2
  log_every_n_steps: 10
  loggers:
    WandbLogger:
      params:
        name: resnet20-rniq
        note: "Trying to sota w4a4"
 
  callbacks:
    ModelCheckpoint:
      params:
        monitor: Loss/ns_val_loss
        mode: min
        filename: rniq_checkpoint-{epoch:02d}-"{Loss/Validation loss:.2f}"
    ReduceLrOnOutlier:
      params:
        reduce_scale: 8
    RandNoiseScale:
      params:
        reduce_scale: 2

data:
  dataset_name: CIFAR10_DALI
  batch_size: 1000
  num_workers: 6


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  act_bit: 4
  weight_bit: 4
  distillation: True
  distillation_loss: Symmetrical KL
  excluded_layers:
    - 'features.init_block.conv'
    - 'output'
